### Pytorch 기본 구성
- **torch** : 메인 네임스페이스로 텐서 등의 다양한 수학 함수가 포함되어져 있으며 Numpy와 유사한 구조 가짐.
- **torch.autograd** : 자동 미분을 위한 함수들이 포함됨. 자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 'Function' 등이 포함.
- **torch.nn** : 신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어져 있음. RNN, LSTM과 같은 레이어, ReLU와 같은 활성화 함수, MSELoss와 같은 손실 함수들이 존재함.
- **torch.optim** : 확률적 경사 하강법(Stochastic Gradient Descent, SGD)를 중심으로 한 파라미터 최적화 알고리즘이 구현.
- **torch.utils.data** : SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함.
- **torch.onnx** : ONNX(Open Neural Network Exchange)의 포맷으로 모델을 익스포트(export)할 때 사용합니다. ONNX는 서로 다른 딥 러닝 프레임워크 간에 모델을 공유할 때 사용하는 포맷
    

### Tensor 조작하기

- Scala : 차원이 존재하지 않는 값.
- Vector : 1차원으로 구성된 값. 1차원 Tensor로도 표현이 가능.
- Matrix : 2차원으로 구성된 값. 2차원 Tensor로도 표현이 가능.
- Tensor : 3차원 이상으로 구성된 값.

#### PyTorch Tensor Shape Convention
- 딥 러닝을 할때 다루고 있는 행렬 또는 텐서의 크기를 고려하는 것은 항상 중요.
    - 2D Tensor(Typical Simple Setting) : 2차원 텐서의 크기 |t|를 (batch size × dimension)으로 표현.
    - 3D Tensor(Typical Computer Vision) : 비전 분야에서의 3차원 Tensor.
    - **3D Tensor(Typical Natural Language Processing) - NLP 분야에서의 3차원 Tensor.**

In [1]:
text = [['나는 사과를 좋아해'], ['나는 바나나를 좋아해'], ['나는 사과를 싫어해'], ['나는 바나나를 싫어해']]


# 각 리스트 내의 문장을 단어별로 분리.
# 결과 :  4 × 3의 크기를 가지는 2D Tensor : 4 x 3 matrix.
text = [''.join(text[i]).split() for i, j in enumerate(text)]


# 단어별 텍스트 문자 벡터화.
# '나는'    = [0.1, 0.2, 0.9]
# '바나나를' = [0.3, 0.5, 0.2]
# '사과를'  = [0.3, 0.5, 0.1]
# '좋아해'  = [0.7, 0.6, 0.5]
# '싫어해'  = [0.5, 0.6, 0.7]

# Train data 재구성. : 4 x 3 x 3 3D Tesor
Text_Vector = [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
             [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
             [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
             [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

# 2개의 배치 사이즈로 구성.
# 각 배치의 텐서의 크기는 2 × 3 × 3. 이는 (batch size, 문장 길이, 단어 벡터의 차원)의 크기를 의미함.
Batch1 = Text_Vector[: 2]
Batch2 = Text_Vector[2:]
print(Batch1)
print(Batch2)

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]], [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]], [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]


In [2]:
# 파이토치 텐서 선언하기.
import torch
import numpy as np

### 1D with PyToch

In [3]:
# 1차원 벡터 만들기.
t = torch.FloatTensor(list(range(7)))
print(t)

# rank, dim
print(f'rank  : {t.dim()}')

# shape.
print(f'shape : {t.shape}')

# size = shape
print(f'size  : {t.size()}')

# slicing.
print(t[2 : 4], t[4 : -2])

# indexing.
print(t[0], t[2])

tensor([0., 1., 2., 3., 4., 5., 6.])
rank  : 1
shape : torch.Size([7])
size  : torch.Size([7])
tensor([2., 3.]) tensor([4.])
tensor(0.) tensor(2.)


### 2D with PyToch

In [4]:
# 2차원 벡터 만들기.
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

# rank, dim
print(f'rank  : {t.dim()}')

# shape.
print(f'shape : {t.shape}')

# size = shape
print(f'size  : {t.size()}')

# slicing.
# 2행 요소값만을 모두 가져옴.
print(t[:, 1])

# indexing.
print(t[0], t[2])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
rank  : 2
shape : torch.Size([4, 3])
size  : torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
tensor([1., 2., 3.]) tensor([7., 8., 9.])


### Broadcasting
- 행렬의 사칙 연산을 쉽게 수행할 수 있도록 PyTorch 내에서 자동으로 크기를 맞춰 연산을 수행하게 도와줌.
- 자동으로 실행되는 기능이므로 결과 문제 발생시, 어디서 문제가 발생했는지 찾기 어려울 수 있므로 주의하여 이용할 필요가 있음.

In [5]:
# 두 행렬의 크기가 같으나, 수학적으로 원래 연산이 불가.
m1 = torch.FloatTensor([3, 3])
m2 = torch.FloatTensor([2, 2])
print( m1 + m2 )

tensor([5., 5.])


In [6]:
# vector + scalar
m3 = torch.FloatTensor([2, 3])

# broadcasting에 의해 [5] => [5, 5] : 차원의 크기를 맞춰줌.
m4 = torch.FloatTensor([5])
print( m3 + m4 )

tensor([7., 8.])


In [7]:
# 2 x 1 vector + 1 x 2 vector
# 수학적으로 계산이 불가한 연산.
# broadcasting에 의해 두 벡터의 크기를 2 x 2로 수정하여 계산함.
# [1, 2] => [[1, 2], [1, 2]]
m5 = torch.FloatTensor([[1, 2]])

# [3], [4] => [[3, 3], [4, 4]]
m6 = torch.FloatTensor([[3], [4]])
print( m5 + m6 )


tensor([[4., 5.],
        [5., 6.]])


### Matrix Multiplication Vs Multiplication
- Matrix Multiplication : matmul()
- Multiplication : mul() or *

In [8]:
# Matrix Multiplication : 일반적인 행렬의 곱셈을 계산함. 

m7 = torch.FloatTensor([[1, 2], [3, 4]])
m8 = torch.FloatTensor([[1], [2]])

# 2 x 2
print('Shape of Matrix 1: ', m1.shape)

# 2 x 1
print('Shape of Matrix 2: ', m2.shape) 

# 2 x 1
print( m7.matmul(m8) ) 

Shape of Matrix 1:  torch.Size([2])
Shape of Matrix 2:  torch.Size([2])
tensor([[ 5.],
        [11.]])


In [9]:
# Multiplication : element-wise 곱셈이 수행됨.
print( m7.mul(m8) ) 
print( m7 * m8 ) 

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [10]:
# 1차원인 경우.
t = torch.FloatTensor([1, 2])
print(t.mean())

# 2차원인 경우.
t2 = torch.FloatTensor([[1, 2], [3, 4]])
print(t2.mean())

# 차원을 인자로 주어 각 행 또는 열별로 평균을 계산.
# 행을 기준 : 0, 열을 기준 : 1
print(t2.mean(dim = 0))
print(t2.mean(dim = 1))

tensor(1.5000)
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


### Sum

In [11]:
# 단순히 원소 전체의 덧셈을 수행.
print(t2.sum()) 

# 열별로 덧셈.
print(t2.sum(dim = 0))

# 행별로 뎃셈.
print(t2.sum(dim = 1)) 

# 행별로 덧셈.
print(t2.sum(dim = -1)) 

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max& ArgMax

In [12]:
print(t2.max())
print()

# 각 열별로 가장 큰값과 해당 인덱스값(argmax)을 반환.
print(t2.max(dim = 0))
print()
print(f' ArgMax : {t2.max(dim = 0)[1]}')
print()

# 각 행별로 가장 큰값과 해당 인덱스값을 반환.
print(t2.max(dim = 1))
print(t2.max(dim = 1))

tensor(4.)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

 ArgMax : tensor([1, 1])

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View
- 원소의 수를 유지하면서 텐서의 크기 변경.
- reshape의 역할.

In [13]:
# 2 x 2 x 3
t3 = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t3)
print(ft.shape)

# 모든 원소의 수 : 12개.
# 3차원(2 x 2 x 3) -> 2차원(2 * 2, 3) = (4, 3)
# -1로 설정되면 다른 차원으로부터 해당값을 유추.
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)
print()

# 3차원 크기 변경.
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)
print()

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])



### Squeeze
- 스퀴즈는 차원이 1인 경우 해당 차원을 제거.

In [14]:
ft2 = torch.FloatTensor([[0], [1], [2]])
print(ft2.shape)

# Squeeze.
# 2차원 벡터가 1차원 벡터로 변경.
print(ft2.squeeze().shape)

torch.Size([3, 1])
torch.Size([3])


### Unsqueeze
- Squeeze의 반대 개념.
- 특정 위치에 1인 차원 추가.

In [15]:
# index가 0부터 시작하므로, 0은 첫번째 차원을 의미함.
ft3 = torch.FloatTensor([0, 1, 2])
print(ft3.shape)

# Unsqueeze.
# 첫번째 차원에 차원을 추가.
print(ft3.unsqueeze(0).shape)

# 두번째 차원에 차원을 추가.
print(ft3.unsqueeze(1).shape)
print(ft3.unsqueeze(-1).shape)

# View.
print(ft3.view(1, -1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])
torch.Size([3, 1])
torch.Size([1, 3])


### Time Casting
- Tensor에는 자료형이라는 것이 존재. ex) torch.FloatTensor, torch.LongTensor, torch.cuda.FloatTensor

In [16]:
lt = torch.LongTensor([1, 2, 3, 4])

# float 타입으로 변경.
print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt.float())

# long 타입으로 변경.
print(bt.long())

tensor([1., 2., 3., 4.])
tensor([1., 0., 0., 1.])
tensor([1, 0, 0, 1])


### Concatenate
- 두 텐서를 연결.

In [17]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

# dim = 0 : 행을 기준.(4 x 2)
print(torch.cat([x, y], dim = 0))

# dim = 1 : 열을 기준.(2 x 4)
print(torch.cat([x, y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking
- 두 텐서를 연결시키는 또 하나의 방법.

In [18]:
# (2,)
x1 = torch.FloatTensor([1, 4])
y1 = torch.FloatTensor([2, 5])
z1 = torch.FloatTensor([3, 6])

# (1, 2) 벡터로 변경후 cat 사용.
print(torch.cat([x1.unsqueeze(0), y1.unsqueeze(0), z1.unsqueeze(0)], dim=0))

# (3, 2)
print(torch.stack([x1, y1, z1]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### ones_like & zeros_like
- ones_like : 1로만 채워진 텐서를 생성.
- zeros_like : 0으로만 채워진 텐서를 생성.

In [19]:
x2 = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x2)
print()

# 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기.
print(torch.ones_like(x2))
print()

# 입력 텐서와 크기를 동일하게 하면서 값을 0로 채우기.
print(torch.zeros_like(x2))

tensor([[0., 1., 2.],
        [2., 1., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In - place Operation
- 변수의 변경된 값을 적용.(덮어쓰기 연산) 

In [20]:
# 2 x 2 tensor.
x3 = torch.FloatTensor([[1, 2], [3, 4]])

# 2를 곱한 결과 출력.
print(x3.mul(2))

# 기존 값 출력.
print(x3)
print()

# 2를 곱한 결과 출력.
# _ 추가함으로써 inplace True값 적용.
print(x3.mul_(2))

# 기존 값 출력.
print(x3)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
